# Generated by Django 5.0.6 on 2024-07-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_registration_dep_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patients',
            new_name='Patient',
        ),
    ]
