# Generated by Django 5.0.6 on 2024-07-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_patients_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='patients',
        ),
    ]
